# Jekyll configuration for Open SDG platform
#
# NOTE: This "production" version only contains differences from _config.yml.
#       See also _data/site_config_prod.yml in this repository.

baseurl: ""
environment: production
# Replace my-github-org and open-sdg-data-starter as needed.
remote_data_prefix: "https://ods-valencia.github.io/data/"

analytics:
  # For production, you likely want to enter a Google Analytics code below.
  ga_prod: ''
